"use client"

import { createContext, useContext, useState, useCallback, useEffect, type ReactNode } from "react"

type Lang = "zh" | "en"

const translations: Record<Lang, Record<string, string>> = {
  zh: {
    // 导航栏
    "nav.features": "功能",
    "nav.cases": "客户案例",
    "nav.pricing": "定价",
    "nav.about": "关于",
    "nav.privacy": "隐私政策",
    "nav.terms": "用户协议",
    "nav.dashboard": "进入仪表盘",
    "nav.login": "登录",
    "nav.register": "免费注册",

    // 侧边栏
    "sidebar.brand": "硫磺督价与采购",
    "sidebar.brandSub": "智能决策系统",
    "sidebar.navMenu": "导航菜单",
    "sidebar.featureModules": "功能模块",
    "sidebar.dashboard": "仪表盘",
    "sidebar.dashboardDesc": "数据概览与价格趋势",
    "sidebar.knowledgeGraph": "价格预测知识图谱",
    "sidebar.knowledgeGraphDesc": "市场资讯、企业经验、制度规则知识库",
    "sidebar.agentChat": "Agent 决策助手",
    "sidebar.agentChatDesc": "智能采购决策支持",
    "sidebar.marketAnalysis": "市场分析",
    "sidebar.marketAnalysisDesc": "价格追踪、品种对比与模型精度",
    "sidebar.reports": "采购报告单",
    "sidebar.reportsDesc": "历史报告与数据分析",
    "sidebar.apiConsole": "API Console",
    "sidebar.apiConsoleDesc": "API Key 管理与文档",
    "sidebar.enterpriseServices": "定制化企业服务",
    "sidebar.manageEnterprise": "管理企业",
    "sidebar.manageEnterpriseTip": "添加或导入新企业",

    // 顶部导航
    "topnav.home": "首页",
    "topnav.title": "硫磺督价与采购智能决策系统",
    "topnav.toggleTheme": "切换主题",
    "topnav.lightMode": "切换浅色模式",
    "topnav.darkMode": "切换深色模式",

    // 面包屑
    "breadcrumb.nav": "面包屑导航",
    "breadcrumb.home": "首页",
    "breadcrumb.agentChat": "智能对话",
    "breadcrumb.enterprises": "企业分析",
    "breadcrumb.enterpriseManage": "企业管理",
    "breadcrumb.reports": "报告中心",
    "breadcrumb.tracker": "市场追踪",
    "breadcrumb.alerts": "异动预警",
    "breadcrumb.subscriptions": "订阅管理",
    "breadcrumb.commodities": "品种对比",
    "breadcrumb.accuracy": "精度分析",
    "breadcrumb.apiConsole": "API 控制台",
    "breadcrumb.knowledgeGraph": "知识图谱",
    "breadcrumb.successCases": "成功案例",
    "breadcrumb.document": "产品文档",
    "breadcrumb.settings": "系统设置",
    "breadcrumb.marketAnalysis": "市场分析",

    // 用户下拉
    "user.login": "登录",
    "user.logout": "退出登录",
    "user.logoutConfirm": "确定要退出登录吗？",
    "user.cancel": "取消",
    "user.confirm": "退出",
    "user.defaultName": "用户",

    // 认证对话框
    "auth.loginTitle": "登录账户",
    "auth.registerTitle": "创建账户",
    "auth.verifyEmailTitle": "验证邮箱",
    "auth.resetPasswordTitle": "重置密码",
    "auth.loginDesc": "登录以保存您的数据和偏好设置",
    "auth.registerDesc": "注册以使用完整功能",
    "auth.verifyEmailDesc": "验证码已发送至",
    "auth.forgotPasswordDesc": "输入邮箱接收密码重置链接",
    "auth.email": "邮箱",
    "auth.emailPlaceholder": "支持 QQ、Gmail、163 等邮箱",
    "auth.password": "密码",
    "auth.passwordPlaceholder": "请输入密码",
    "auth.name": "姓名",
    "auth.namePlaceholder": "请输入姓名",
    "auth.confirmPassword": "确认密码",
    "auth.confirmPasswordPlaceholder": "请再次输入密码",
    "auth.login": "登录",
    "auth.sendCode": "发送验证码",
    "auth.completeRegistration": "完成注册",
    "auth.goBack": "返回修改",
    "auth.forgotPassword": "忘记密码？",
    "auth.noAccount": "还没有账户？",
    "auth.hasAccount": "已有账户？",
    "auth.registerNow": "立即注册",
    "auth.loginNow": "立即登录",
    "auth.verifyCode": "验证码",
    "auth.verifyCodePlaceholder": "请输入 6 位验证码",
    "auth.resend": "重发",
    "auth.enterEmailDesc": "输入您的邮箱地址，我们将发送验证码。",
    "auth.enterEmailPlaceholder": "请输入注册邮箱",
    "auth.backToLogin": "返回登录",
    "auth.verifyAndSendReset": "验证并发送重置链接",
    "auth.passwordResetSuccess": "密码重置成功",
    "auth.passwordResetSuccessDesc": "您的密码已成功重置，请使用新密码登录。",
    "auth.ok": "确定",
    "auth.forgotPasswordTitle": "忘记密码",
    "auth.forgotPasswordDesc2": "输入您的邮箱获取验证码，然后设置新密码",
    "auth.devCodePrefix": "开发环境测试验证码：",
    "auth.devCodeSent": "验证码已发送到控制台，开发环境测试验证码：",
    "auth.newPassword": "新密码",
    "auth.newPasswordPlaceholder": "请输入新密码",
    "auth.confirmNewPasswordPlaceholder": "请再次输入新密码",
    "auth.resetPassword": "重置密码",
    "auth.rememberPassword": "想起密码了？",
    "auth.sendCodeAgain": "重新发送",
    "auth.resetLinkSent": "密码重置链接已发送至您的邮箱，请查收。",

    // 认证错误
    "auth.error.invalidEmail": "请输入有效的邮箱地址",
    "auth.error.passwordMismatch": "两次输入的密码不一致",
    "auth.error.passwordTooShort": "密码长度至少为 8 位",
    "auth.error.passwordWeak": "密码强度不足，请至少满足 2 项要求",
    "auth.error.passwordStrength": "密码强度不足",
    "auth.error.codeRequired": "请输入验证码",
    "auth.error.codeWrong": "验证码错误",
    "auth.error.sendCodeFailed": "发送验证码失败",
    "auth.error.sendCodeRetry": "发送验证码失败，请稍后重试",
    "auth.error.loginFailed": "登录失败",
    "auth.error.loginRetry": "登录失败，请稍后重试",
    "auth.error.registerFailed": "注册失败",
    "auth.error.registerRetry": "注册失败，请稍后重试",
    "auth.error.verifyFailed": "验证失败，请稍后重试",
    "auth.error.sendResetFailed": "发送重置邮件失败",
    "auth.error.sendResetRetry": "发送重置邮件失败，请稍后重试",
    "auth.error.resetFailed": "重置密码失败",
    "auth.error.resetRetry": "重置密码失败，请稍后重试",

    // 密码强度
    "auth.pw.veryWeak": "非常弱",
    "auth.pw.weak": "弱",
    "auth.pw.medium": "中等",
    "auth.pw.strong": "强",
    "auth.pw.veryStrong": "非常强",
    "auth.pw.checkLength": "至少 8 个字符",
    "auth.pw.checkUpper": "包含大写字母",
    "auth.pw.checkLower": "包含小写字母",
    "auth.pw.checkNumber": "包含数字",
    "auth.pw.checkSpecial": "包含特殊字符",

    // 手机号登录
    "auth.phoneLogin": "手机号登录",
    "auth.phoneLoginDesc": "使用手机验证码快速登录",
    "auth.phone": "手机号",
    "auth.phonePlaceholder": "请输入手机号",
    "auth.error.invalidPhone": "请输入正确的手机号",
    "auth.noAccountPhone": "没有账号？",
    "auth.useEmailRegister": "使用邮箱注册",
    "auth.phoneCodePlaceholder": "请输入验证码",

    // 仪表盘
    "dashboard.title": "仪表盘",
    "dashboard.priceOverview": "价格概览",
    "dashboard.inventoryOverview": "库存概览",
    "dashboard.enterprisePredictions": "企业预测",
    "dashboard.currentPrice": "当前价格",
    "dashboard.priceChange": "涨跌幅",
    "dashboard.riskHigh": "高",
    "dashboard.riskMedium": "中等",
    "dashboard.riskLow": "低",
    "dashboard.latestReports": "最新报告",
    "dashboard.viewAll": "查看全部",
    "dashboard.noData": "暂无数据",
    "dashboard.avgPrice": "均价",
    "dashboard.trend": "趋势",
    "dashboard.heat": "热度",
    "dashboard.risk": "风险",
    "dashboard.trend30d": "近30日走势",
    "dashboard.monthlyTrendJudgment": "月度价格趋势判断",
    "dashboard.demandActivity": "采购需求活跃度",
    "dashboard.riskAssessment": "采购决策风险评估",
    "dashboard.ruleBased30d": "规则评估 · 基于近30日价格波动",
    "dashboard.dataUpdatedPrefix": "数据更新: ",
    "dashboard.priceSourcePrefix": "价格来源: ",
    "dashboard.invSourcePrefix": "库存来源: ",
    "dashboard.sourcePrefix": "来源: ",
    "dashboard.commodityCoverage": "品种覆盖",
    "dashboard.varietiesUnit": "品种",
    "dashboard.modelAccuracy": "模型精度",
    "dashboard.excellent": "优秀",
    "dashboard.mcpTools": "MCP 工具",
    "dashboard.countUnit": "个",
    "dashboard.enterpriseAccess": "企业接入",
    "dashboard.householdsUnit": "家",
    "dashboard.expanding": "扩展中",
    "dashboard.selected": "已选中",
    "dashboard.switch": "切换",
    "dashboard.marketInsight": "市场洞察",
    "dashboard.deepAnalysis": "深入分析",
    "dashboard.priceGraph": "价格知识图谱",
    "dashboard.energyFlow": "能量流动",
    "dashboard.weeklyReport": "采购周报",
    "dashboard.enterprisePricePredictions": "企业价格预测",
    "dashboard.avgPredictedPricePrefix": "平均预测价格：",
    "dashboard.perTon": "/吨",
    "dashboard.more": "更多",
    "dashboard.details": "详情",
    "dashboard.loadingMarket": "加载市场数据...",
    "dashboard.loadFailed": "数据加载失败",
    "dashboard.noCommodityDataPrefix": "暂无",
    "dashboard.noCommodityDataSuffix": "价格数据",
    "dashboard.refreshingPrefix": "正在刷新 ",
    "dashboard.refreshingSuffix": " 数据...",
    "dashboard.spotAvg": "现货均价",
    "dashboard.simulatedData": "模拟数据",
    "dashboard.modelDerived": "模型推算",
    "dashboard.realData": "真实数据",
    "dashboard.priceSeriesCalc": "价格序列计算",
    "dashboard.freshness.unknown": "未知",
    "dashboard.freshness.today": "今日更新",
    "dashboard.freshness.oneDayAgo": "1 天前",
    "dashboard.freshness.daysAgoSuffix": " 天前",
    "dashboard.heat.hot": "旺盛",
    "dashboard.heat.active": "活跃",
    "dashboard.heat.mild": "温和",
    "dashboard.heat.noData": "暂无数据",
    "dashboard.heatLabel.hot": "需求旺盛",
    "dashboard.heatLabel.balanced": "供需平衡",
    "dashboard.heatLabel.general": "需求一般",
    "dashboard.heatLabel.noData": "待接入库存数据",
    "dashboard.riskLabel.volatile": "波动较大",
    "dashboard.riskLabel.watch": "关注走势",
    "dashboard.riskLabel.stable": "相对稳定",
    "dashboard.trend.up": "上涨",
    "dashboard.trend.down": "下跌",
    "dashboard.trend.flat": "震荡",
    "dashboard.commodityList": "硫磺·磷矿·钾肥·尿素",
    "dashboard.mcpToolsDesc": "查询·预测·对比·精度",
    "dashboard.graph.price": "价格",
    "dashboard.graph.supply": "供给",
    "dashboard.graph.demand": "需求",
    "dashboard.graph.cost": "成本",
    "dashboard.graph.policy": "政策",

    // 市场分析
    "marketAnalysis.title": "市场分析",
    "marketAnalysis.desc": "价格追踪、品种对比与模型精度评估",
    "marketAnalysis.tracker": "Tracker 追踪",
    "marketAnalysis.commodities": "品种对比",
    "marketAnalysis.accuracy": "精度分析",

    // 报告
    "reports.title": "采购报告单",
    "reports.trend.up": "上涨",
    "reports.trend.slightUp": "小幅上涨",
    "reports.trend.down": "下跌",
    "reports.trend.slightDown": "小幅下跌",
    "reports.trend.stable": "稳定",
    "reports.trend.volatile": "震荡",
    "reports.recommend.stockUp": "建议备库",
    "reports.recommend.urgent": "紧急采购",
    "reports.recommend.moderate": "适当备库",
    "reports.recommend.wait": "观望",
    "reports.recommend.asNeeded": "按需采购",
    "reports.risk.high": "高",
    "reports.risk.medium": "中等",
    "reports.risk.low": "低",
    "reports.riskSuffix": "风险",
    "reports.exportWord": "导出 Word",
    "reports.exportExcel": "导出 Excel",
    "reports.discussInChat": "在对话中讨论",
    "reports.searchPlaceholder": "搜索报告...",
    "reports.filterByType": "按类型筛选",
    "reports.filterByRisk": "按风险筛选",
    "reports.filterByTrend": "按趋势筛选",
    "reports.all": "全部",
    "reports.generateReport": "生成报告",
    "reports.keyword": "关键词",
    "reports.clearFilters": "清除",
    "reports.noReports": "暂无报告",
    "reports.priceChart": "价格走势",

    // 企业管理
    "enterpriseManage.title": "企业管理",
    "enterpriseManage.addEnterprise": "添加企业",
    "enterpriseManage.importExcel": "导入 Excel",
    "enterpriseManage.downloadTemplate": "下载模板",
    "enterpriseManage.deleteEnterprise": "删除企业",
    "enterpriseManage.editEnterprise": "编辑企业",
    "enterpriseManage.searchPlaceholder": "搜索企业...",
    "enterpriseManage.noEnterprises": "暂无企业",
    "enterpriseManage.confirmDelete": "确定要删除该企业吗？",
    "enterpriseManage.createEnterprise": "创建企业",
    "enterpriseManage.updateEnterprise": "更新企业",
    "enterpriseManage.enterpriseName": "企业名称",
    "enterpriseManage.enterpriseCode": "企业代码",
    "enterpriseManage.shortDescription": "简短描述",
    "enterpriseManage.color": "颜色",
    "enterpriseManage.industry": "行业",
    "enterpriseManage.province": "省份",
    "enterpriseManage.city": "城市",
    "enterpriseManage.importSuccess": "导入成功",
    "enterpriseManage.importPartial": "部分导入成功",
    "enterpriseManage.enterpriseNamePlaceholder": "请输入企业名称",
    "enterpriseManage.enterpriseCodePlaceholder": "请输入企业代码（英文）",
    "enterpriseManage.shortDescriptionPlaceholder": "请输入简短描述",
    "enterpriseManage.desc": "管理需要分析的企业信息，支持导入新企业",
    "enterpriseManage.totalPrefix": "共 ",
    "enterpriseManage.totalSuffix": " 家企业",
    "enterpriseManage.preset": "预设",
    "enterpriseManage.unknownRegion": "未知地区",
    "enterpriseManage.capacity": "产能：",
    "enterpriseManage.tenKtonPerYear": " 万吨/年",
    "enterpriseManage.transport": "运输：",
    "enterpriseManage.stock": "库存：",
    "enterpriseManage.ton": " 吨",
    "enterpriseManage.strategy": "策略：",
    "enterpriseManage.viewDetailLink": "查看价格影响因子权重和预测趋势 →",
    "enterpriseManage.dialogEditDesc": "修改企业信息",
    "enterpriseManage.dialogAddDesc": "填写新企业信息，带 * 为必填项",
    "enterpriseManage.enterpriseFullName": "企业全称",
    "enterpriseManage.codeExamplePlaceholder": "如: example_corp",
    "enterpriseManage.location": "所在地区",
    "enterpriseManage.locationPlaceholder": "如: 华东地区",
    "enterpriseManage.provincePlaceholder": "如: 山东",
    "enterpriseManage.capacityLabel": "产能(万吨/年)",
    "enterpriseManage.transportMode": "运输方式",
    "enterpriseManage.inventoryStrategy": "库存策略",
    "enterpriseManage.mainProducts": "主要产品",
    "enterpriseManage.productsPlaceholder": "用逗号分隔，如: 磷酸一铵,尿素",
    "enterpriseManage.customerRegions": "客户区域",
    "enterpriseManage.regionsPlaceholder": "用逗号分隔，如: 华东,华南",
    "enterpriseManage.description": "企业描述",
    "enterpriseManage.descriptionPlaceholder": "详细描述企业情况...",
    "enterpriseManage.shortDescPlaceholder": "用于侧边栏显示",
    "enterpriseManage.uiColor": "UI颜色",
    "enterpriseManage.inventorySection": "库存与采购信息",
    "enterpriseManage.currentStock": "当前库存(吨)",
    "enterpriseManage.maxCapacity": "最大仓储(吨)",
    "enterpriseManage.safetyDays": "安全库存天数",
    "enterpriseManage.avgConsumption": "日均消耗(吨/天)",
    "enterpriseManage.supplierCount": "供应商数量",
    "enterpriseManage.portDistance": "距港口(公里)",
    "enterpriseManage.priceConfigSection": "价格预测配置",
    "enterpriseManage.basePrice": "基准价格",
    "enterpriseManage.lastPurchaseDate": "上次采购日期",
    "enterpriseManage.importDesc": "支持 JSON 和 CSV 格式的文件导入",
    "enterpriseManage.uploadHint": "点击上传或拖拽文件到此处",
    "enterpriseManage.importFormats": "支持 JSON、CSV 格式",
    "enterpriseManage.successCount": "成功: ",
    "enterpriseManage.skippedCount": "跳过: ",
    "enterpriseManage.failedCount": "失败: ",
    "enterpriseManage.error.fetchFailed": "获取企业列表失败",
    "enterpriseManage.error.saveFailed": "保存企业失败",
    "enterpriseManage.error.deleteFailed": "删除企业失败",
    "enterpriseManage.error.importFailed": "导入失败，请检查文件格式",
    "enterpriseManage.error.invalidFile": "请上传 JSON 或 CSV 文件",
    "enterpriseManage.error.staticDelete": "静态企业（HX集团、HY集团、TC集团）不允许删除",
    "enterpriseManage.color.cyan": "青色",
    "enterpriseManage.color.violet": "紫色",
    "enterpriseManage.color.amber": "琥珀色",
    "enterpriseManage.color.emerald": "翠绿色",
    "enterpriseManage.color.rose": "玫瑰色",
    "enterpriseManage.color.blue": "蓝色",
    "enterpriseManage.transport.water": "水运",
    "enterpriseManage.transport.rail": "铁路",
    "enterpriseManage.transport.road": "公路",
    "enterpriseManage.strategy.aggressive": "激进",
    "enterpriseManage.strategy.moderate": "稳健",
    "enterpriseManage.strategy.conservative": "保守",

    // 企业列表
    "enterprises.title": "企业分析",
    "enterprises.searchPlaceholder": "搜索企业名称、行业、产品...",
    "enterprises.filterIndustry": "筛选行业",
    "enterprises.filterProvince": "筛选省份",
    "enterprises.allIndustries": "全部行业",
    "enterprises.allProvinces": "全部省份",
    "enterprises.total": "企业总数",
    "enterprises.listed": "上市企业",
    "enterprises.unlisted": "非上市企业",
    "enterprises.industries": "行业数量",
    "enterprises.provinces": "覆盖省份",
    "enterprises.lastUpdated": "最后更新",
    "enterprises.viewDetail": "查看详情",
    "enterprises.website": "官网",
    "enterprises.products": "主要产品",
    "enterprises.employees": "员工人数",
    "enterprises.founded": "成立年份",
    "enterprises.revenue": "年营收",
    "enterprises.sampleNote": "示例数据 · 企业信息已匿名化处理 · 最后更新: ",
    "enterprises.totalPrefix": "共 ",
    "enterprises.totalSuffix": " 家企业",
    "enterprises.filterTitle": "筛选条件",
    "enterprises.foundPrefix": "找到 ",
    "enterprises.foundSuffix": " 家企业",
    "enterprises.listedBadge": "上市",
    "enterprises.mainProductsLabel": "主要产品：",
    "enterprises.revenueLabel": "营收：",
    "enterprises.employeesLabel": "员工：",
    "enterprises.websiteLink": "访问官网 →",

    // Agent 对话
    "chat.title": "Agent 决策助手",
    "chat.newConversation": "新建对话",
    "chat.deleteConversation": "删除对话",
    "chat.inputPlaceholder": "输入您的问题...",
    "chat.send": "发送",
    "chat.copy": "复制",
    "chat.regenerate": "重新生成",
    "chat.thinking": "思考中...",
    "chat.noConversations": "暂无对话",
    "chat.uploadImage": "上传图片",
    "chat.clearConversation": "清空对话",
    "chat.welcomeTitle": "硫磺采购智能助手",
    "chat.welcomeDesc": "我可以帮您分析市场趋势、预测价格走势、生成采购建议",
    "chat.suggestions": "试试这些问题",
    "chat.exportReport": "导出报告",
    "chat.regenerateAnswer": "重新回答",
    "chat.generateReport": "生成报告",
    "chat.copied": "已复制",
    "chat.mayAlsoAsk": "您可能还想了解：",
    "chat.agentThinking": "Agent 思考中...",
    "chat.login": "登录",
    "chat.noHistory": "暂无历史对话",
    "chat.advisorTitle": "硫磺采购顾问",
    "chat.onlineStatus": "在线 · 随时为您解答",
    "chat.systemArchitecture": "系统架构",
    "chat.quickQuestions": "快捷提问",
    "chat.usageTips": "使用提示",
    "chat.howToUse": "如何更好地使用助手",
    "chat.deepAnalysis": "深度分析",
    "chat.advancedTips": "进阶提问技巧",
    "chat.subtitle": "基于 AI 的智能采购决策支持",
    "chat.synced": "历史记录已同步",
    "chat.savePrompt": "登录后可保存对话",
    "chat.inputPlaceholderImage": "添加描述或直接发送...",
    "chat.inputPlaceholderPaste": "输入您的问题（支持粘贴图片）...",
    "chat.previewImage": "预览图片",
    "chat.noContentReport": "暂无对话内容可生成报告",
    "chat.reportGeneratedPrefix": "报告已生成：",
    "chat.reportFailed": "生成报告失败，请稍后重试",
    "chat.suggested.trend": "当前硫磺市场趋势如何？",
    "chat.suggested.weekAdvice": "未来一周采购建议是什么？",
    "chat.suggested.inventory": "库存水平是否需要调整？",
    "chat.suggested.supplierCompare": "主要供应商报价对比",
    "chat.suggested.volatilityCause": "分析近期价格波动原因",
    "chat.suggested.nextMonth": "预测下个月价格走势",
    "chat.suggested.report": "生成采购决策分析报告",
    "chat.suggested.freightCost": "国际运费对成本的影响",
    "chat.followUp.price.rise": "价格还会继续上涨吗？",
    "chat.followUp.price.factors": "什么因素影响价格波动？",
    "chat.followUp.price.yoy": "与去年同期价格对比如何？",
    "chat.followUp.price.timing": "最佳采购时机是什么时候？",
    "chat.followUp.stock.turnover": "当前库存周转天数是多少？",
    "chat.followUp.stock.safety": "建议的安全库存量是多少？",
    "chat.followUp.stock.cost": "如何优化库存成本？",
    "chat.followUp.stock.port": "各港口库存分布情况？",
    "chat.followUp.purchase.nowOrWait": "应该立即采购还是观望？",
    "chat.followUp.purchase.quantity": "建议采购数量是多少？",
    "chat.followUp.purchase.splitOrCentral": "分散采购还是集中采购？",
    "chat.followUp.purchase.risk": "如何降低采购风险？",
    "chat.followUp.trend.month": "未来一个月趋势预测？",
    "chat.followUp.trend.seasonal": "季节性因素如何影响？",
    "chat.followUp.trend.international": "国际市场趋势如何？",
    "chat.followUp.trend.demand": "需求端变化趋势？",
    "chat.followUp.risk.main": "主要风险因素有哪些？",
    "chat.followUp.risk.priceHedge": "如何规避价格风险？",
    "chat.followUp.risk.supplyChain": "供应链风险如何应对？",
    "chat.followUp.risk.exchange": "汇率波动影响多大？",
    "chat.followUp.default.elaborate": "能否详细解释一下？",
    "chat.followUp.default.basis": "这个结论的数据依据是什么？",
    "chat.followUp.default.action": "有什么行动建议？",
    "chat.tip.specific": "提问时尽量具体，包含时间范围",
    "chat.tip.table": "可以要求生成数据对比表格",
    "chat.tip.followUp": "支持追问和多轮对话",
    "chat.tip.report": "可请求生成采购建议报告",
    "chat.tip.clickFollowUp": "点击追问按钮快速深入了解",
    "chat.tip.explainSource": "要求解释数据来源和计算方法",
    "chat.tip.scenarios": "询问不同情景下的分析",
    "chat.tip.compare": "请求对比多个供应商/地区",
    "chat.tip.risks": "让 AI 列出风险和不确定性",

    // API Console
    "apiConsole.title": "API Console",
    "apiConsole.desc": "API Key 管理与接口文档",
    "apiConsole.createKey": "创建 API Key",
    "apiConsole.keyName": "Key 名称",
    "apiConsole.keyNamePlaceholder": "请输入 Key 名称",
    "apiConsole.create": "创建",
    "apiConsole.cancel": "取消",
    "apiConsole.yourKeys": "您的 API Keys",
    "apiConsole.noKeys": "暂无 API Key",
    "apiConsole.quota": "配额",
    "apiConsole.used": "已用",
    "apiConsole.remaining": "剩余",
    "apiConsole.copyKey": "复制 Key",
    "apiConsole.copied": "已复制",
    "apiConsole.deleteKey": "删除 Key",
    "apiConsole.resetKey": "重置 Key",
    "apiConsole.keyCreated": "Key 创建成功",
    "apiConsole.keyCreatedWarning": "请妥善保存此 API Key，创建后将不再显示完整值",
    "apiConsole.confirmDeleteKey": "确定要删除此 API Key 吗？",
    "apiConsole.confirmResetKey": "确定要重置此 API Key 吗？重置后旧 Key 将立即失效。",
    "apiConsole.apiDocs": "接口文档",
    "apiConsole.baseUrl": "基础地址",
    "apiConsole.authMethod": "认证方式",
    "apiConsole.rateLimit": "速率限制",
    "apiConsole.requestsPerMinute": "请求/分钟",
    "apiConsole.endpoints": "接口列表",
    "apiConsole.createKeyBtn": "创建 Key",
    "apiConsole.quotaInfo": "API 配额（本月剩余）",
    "apiConsole.free": "免费",
    "apiConsole.paid": "付费",
    "apiConsole.totalPrefix": "共 ",
    "apiConsole.totalSuffix": " 次",
    "apiConsole.emptyDesc": "创建一个 API Key 开始使用 API 服务",
    "apiConsole.inactive": "已禁用",
    "apiConsole.createdAt": "创建于 ",
    "apiConsole.lastUsed": " · 最后使用 ",
    "apiConsole.reset": "重置",
    "apiConsole.limitReached": "API Key 数量已达上限（最多 5 个）",
    "apiConsole.keyNamePlaceholderExample": "例如：生产环境 Key",
    "apiConsole.keyNameDesc": "为 API Key 设置一个易于识别的名称",
    "apiConsole.copy": "复制",
    "apiConsole.done": "完成",
    "apiConsole.resetTitle": "API Key 已重置",
    "apiConsole.resetWarning": "旧 Key 已失效，请保存新的 Key",
    "apiConsole.createFailed": "创建失败",
    "apiConsole.deleteFailed": "删除失败",
    "apiConsole.resetFailed": "重置失败",
    "apiConsole.tabPrices": "价格查询",
    "apiConsole.tabPredict": "价格预测",
    "apiConsole.tabDecision": "决策建议",
    "apiConsole.tabInventory": "库存数据",
    "apiConsole.tabNews": "市场新闻",
    "apiConsole.tabChat": "AI 聊天",
    "apiConsole.descPrices": "获取硫磺价格历史数据",
    "apiConsole.descPredict": "预测未来硫磺价格",
    "apiConsole.descDecision": "获取采购决策建议",
    "apiConsole.descInventory": "获取港口库存数据",
    "apiConsole.descNews": "获取市场新闻动态",
    "apiConsole.descChat": "与 AI 聊天助手对话",
    "apiConsole.requestParams": "请求参数",
    "apiConsole.requestBody": "请求体",
    "apiConsole.exampleCode": "示例代码",
    "apiConsole.paramName": "参数",
    "apiConsole.paramType": "类型",
    "apiConsole.paramDesc": "说明",
    "apiConsole.startDate": "开始日期 (YYYY-MM-DD)",
    "apiConsole.endDate": "结束日期 (YYYY-MM-DD)",
    "apiConsole.regionFilter": "地区筛选",
    "apiConsole.marketFilter": "市场筛选",
    "apiConsole.portFilter": "港口筛选",
    "apiConsole.keywordFilter": "关键词筛选",
    "apiConsole.returnCount30": "返回数量 (默认 30)",
    "apiConsole.returnCount20": "返回数量 (默认 20)",

    // API Keys 页面
    "apiKeys.title": "API Keys 管理",
    "apiKeys.createKey": "创建 API Key",
    "apiKeys.noKeys": "暂无 API Key，点击上方按钮创建",
    "apiKeys.active": "活跃",
    "apiKeys.inactive": "已停用",
    "apiKeys.neverUsed": "从未使用",
    "apiKeys.createdAt": "创建时间",
    "apiKeys.lastUsed": "最后使用",
    "apiKeys.expiresAt": "过期时间",
    "apiKeys.quotaTitle": "配额使用情况",
    "apiKeys.requestsUsed": "已使用请求数",
    "apiKeys.desc": "管理你的 API 密钥和配额",
    "apiKeys.apiDocs": "API 文档",
    "apiKeys.quotaBalance": "配额余额",
    "apiKeys.freeQuota": "免费额度",
    "apiKeys.paidQuota": "付费额度",
    "apiKeys.totalRemaining": "总剩余",
    "apiKeys.createNewKey": "创建新 API Key",
    "apiKeys.keyNamePlaceholder": "Key 名称（如：生产环境）",
    "apiKeys.saveKeyWarning": "请保存此 API Key",
    "apiKeys.keyShownOnce": "此 Key 仅显示一次，关闭后将无法再次查看完整值",
    "apiKeys.yourKeys": "已创建的 API Keys",
    "apiKeys.maxKeys": "最多可创建 5 个 API Key",
    "apiKeys.noKeysHint": "暂无 API Key，请创建一个",
    "apiKeys.createdAtLabel": "创建: ",
    "apiKeys.lastUsedLabel": "最后使用: ",
    "apiKeys.error.nameRequired": "请先填写 Key 名称",
    "apiKeys.error.createRetry": "创建失败，请稍后重试",
    "apiKeys.error.resetRetry": "重置失败，请稍后重试",
    "apiKeys.confirmReset": "重置后旧 Key 将失效，确定继续？",

    // 通用
    "common.loading": "加载中...",
    "common.error": "出错了",
    "common.save": "保存",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.search": "搜索",
    "common.export": "导出",
    "common.import": "导入",
    "common.create": "创建",
    "common.close": "关闭",
    "common.confirm": "确认",
    "common.cancel": "取消",
    "common.retry": "重试",
    "common.noData": "暂无数据",
    "common.success": "操作成功",
    "common.failed": "操作失败",
    "common.viewDetail": "查看详情",
    "common.back": "返回",
    "common.yes": "是",
    "common.no": "否",

    // Landing Page
    "landing.hero.title": "AI 驱动的智能决策",
    "landing.hero.subtitle": "硫磺督价与采购",
    "landing.hero.desc": "智能决策系统",
    "landing.hero.cta": "立即体验",
    "landing.hero.learnMore": "了解更多",
    "landing.features.title": "核心能力",
    "landing.features.subtitle": "四大智能模块",
    "landing.stats.accuracy": "预测准确率",
    "landing.stats.enterprises": "服务企业",
    "landing.stats.data": "历史数据",
    "landing.stats.monitoring": "实时监控",
    "landing.about.title": "为什么选择我们",
    "landing.cta.title": "开始智能采购之旅",
    "landing.cta.button": "免费开始使用",
  },
  en: {
    // Navigation
    "nav.features": "Features",
    "nav.cases": "Cases",
    "nav.pricing": "Pricing",
    "nav.about": "About",
    "nav.privacy": "Privacy",
    "nav.terms": "Terms",
    "nav.dashboard": "Dashboard",
    "nav.login": "Sign In",
    "nav.register": "Get Started",

    // Sidebar
    "sidebar.brand": "Sulfur Procurement",
    "sidebar.brandSub": "Smart Decision System",
    "sidebar.navMenu": "Navigation",
    "sidebar.featureModules": "Feature Modules",
    "sidebar.dashboard": "Dashboard",
    "sidebar.dashboardDesc": "Data Overview & Price Trends",
    "sidebar.knowledgeGraph": "Knowledge Graph",
    "sidebar.knowledgeGraphDesc": "Market Info, Enterprise Experience & Knowledge Base",
    "sidebar.agentChat": "Agent Assistant",
    "sidebar.agentChatDesc": "Smart Procurement Decision Support",
    "sidebar.marketAnalysis": "Market Analysis",
    "sidebar.marketAnalysisDesc": "Price Tracking, Comparison & Model Accuracy",
    "sidebar.reports": "Procurement Reports",
    "sidebar.reportsDesc": "Historical Reports & Data Analysis",
    "sidebar.apiConsole": "API Console",
    "sidebar.apiConsoleDesc": "API Key Management & Docs",
    "sidebar.enterpriseServices": "Enterprise Services",
    "sidebar.manageEnterprise": "Manage Enterprises",
    "sidebar.manageEnterpriseTip": "Add or import new enterprise",

    // Top Navigation
    "topnav.home": "Home",
    "topnav.title": "Sulfur Procurement Intelligent Decision System",
    "topnav.toggleTheme": "Toggle Theme",
    "topnav.lightMode": "Switch to Light Mode",
    "topnav.darkMode": "Switch to Dark Mode",

    // Breadcrumb
    "breadcrumb.nav": "Breadcrumb",
    "breadcrumb.home": "Home",
    "breadcrumb.agentChat": "Agent Chat",
    "breadcrumb.enterprises": "Enterprise Analysis",
    "breadcrumb.enterpriseManage": "Enterprise Management",
    "breadcrumb.reports": "Reports",
    "breadcrumb.tracker": "Market Tracker",
    "breadcrumb.alerts": "Alerts",
    "breadcrumb.subscriptions": "Subscriptions",
    "breadcrumb.commodities": "Commodity Comparison",
    "breadcrumb.accuracy": "Accuracy Analysis",
    "breadcrumb.apiConsole": "API Console",
    "breadcrumb.knowledgeGraph": "Knowledge Graph",
    "breadcrumb.successCases": "Success Cases",
    "breadcrumb.document": "Documentation",
    "breadcrumb.settings": "Settings",
    "breadcrumb.marketAnalysis": "Market Analysis",

    // User Dropdown
    "user.login": "Sign In",
    "user.logout": "Sign Out",
    "user.logoutConfirm": "Are you sure you want to sign out?",
    "user.cancel": "Cancel",
    "user.confirm": "Sign Out",
    "user.defaultName": "User",

    // Auth Dialog
    "auth.loginTitle": "Sign In",
    "auth.registerTitle": "Create Account",
    "auth.verifyEmailTitle": "Verify Email",
    "auth.resetPasswordTitle": "Reset Password",
    "auth.loginDesc": "Sign in to save your data and preferences",
    "auth.registerDesc": "Register to access all features",
    "auth.verifyEmailDesc": "Verification code sent to",
    "auth.forgotPasswordDesc": "Enter email to receive password reset link",
    "auth.email": "Email",
    "auth.emailPlaceholder": "Supports QQ, Gmail, 163, etc.",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "Enter password",
    "auth.name": "Name",
    "auth.namePlaceholder": "Enter name",
    "auth.confirmPassword": "Confirm Password",
    "auth.confirmPasswordPlaceholder": "Re-enter password",
    "auth.login": "Sign In",
    "auth.sendCode": "Send Code",
    "auth.completeRegistration": "Complete Registration",
    "auth.goBack": "Go Back",
    "auth.forgotPassword": "Forgot Password?",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.registerNow": "Register Now",
    "auth.loginNow": "Sign In Now",
    "auth.verifyCode": "Verification Code",
    "auth.verifyCodePlaceholder": "Enter 6-digit code",
    "auth.resend": "Resend",
    "auth.enterEmailDesc": "Enter your email to receive a verification code.",
    "auth.enterEmailPlaceholder": "Enter registered email",
    "auth.backToLogin": "Back to Sign In",
    "auth.verifyAndSendReset": "Verify & Send Reset Link",
    "auth.passwordResetSuccess": "Password Reset Successful",
    "auth.passwordResetSuccessDesc": "Password reset successfully. Please sign in with your new password.",
    "auth.ok": "OK",
    "auth.forgotPasswordTitle": "Forgot Password",
    "auth.forgotPasswordDesc2": "Enter email for verification code, then set new password",
    "auth.devCodePrefix": "Dev Test Code: ",
    "auth.devCodeSent": "Verification code sent to console. Dev Test Code: ",
    "auth.newPassword": "New Password",
    "auth.newPasswordPlaceholder": "Enter new password",
    "auth.confirmNewPasswordPlaceholder": "Re-enter new password",
    "auth.resetPassword": "Reset Password",
    "auth.rememberPassword": "Remembered your password?",
    "auth.sendCodeAgain": "Resend",
    "auth.resetLinkSent": "Password reset link has been sent to your email.",

    // Auth Errors
    "auth.error.invalidEmail": "Please enter a valid email address",
    "auth.error.passwordMismatch": "Passwords do not match",
    "auth.error.passwordTooShort": "Password must be at least 8 characters",
    "auth.error.passwordWeak": "Password too weak, meet at least 2 requirements",
    "auth.error.passwordStrength": "Password too weak",
    "auth.error.codeRequired": "Please enter verification code",
    "auth.error.codeWrong": "Invalid verification code",
    "auth.error.sendCodeFailed": "Failed to send verification code",
    "auth.error.sendCodeRetry": "Failed to send code, please try again later",
    "auth.error.loginFailed": "Sign in failed",
    "auth.error.loginRetry": "Sign in failed, please try again later",
    "auth.error.registerFailed": "Registration failed",
    "auth.error.registerRetry": "Registration failed, please try again later",
    "auth.error.verifyFailed": "Verification failed, please try again later",
    "auth.error.sendResetFailed": "Failed to send reset email",
    "auth.error.sendResetRetry": "Failed to send reset email, please try again later",
    "auth.error.resetFailed": "Password reset failed",
    "auth.error.resetRetry": "Password reset failed, please try again later",

    // Password Strength
    "auth.pw.veryWeak": "Very Weak",
    "auth.pw.weak": "Weak",
    "auth.pw.medium": "Medium",
    "auth.pw.strong": "Strong",
    "auth.pw.veryStrong": "Very Strong",
    "auth.pw.checkLength": "At least 8 characters",
    "auth.pw.checkUpper": "Contains uppercase",
    "auth.pw.checkLower": "Contains lowercase",
    "auth.pw.checkNumber": "Contains number",
    "auth.pw.checkSpecial": "Contains special character",

    // Phone Login
    "auth.phoneLogin": "Phone Sign In",
    "auth.phoneLoginDesc": "Quick sign in with phone verification",
    "auth.phone": "Phone Number",
    "auth.phonePlaceholder": "Enter phone number",
    "auth.error.invalidPhone": "Please enter a valid phone number",
    "auth.noAccountPhone": "No account?",
    "auth.useEmailRegister": "Register with Email",
    "auth.phoneCodePlaceholder": "Enter verification code",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.priceOverview": "Price Overview",
    "dashboard.inventoryOverview": "Inventory Overview",
    "dashboard.enterprisePredictions": "Enterprise Predictions",
    "dashboard.currentPrice": "Current Price",
    "dashboard.priceChange": "Change",
    "dashboard.riskHigh": "High",
    "dashboard.riskMedium": "Medium",
    "dashboard.riskLow": "Low",
    "dashboard.latestReports": "Latest Reports",
    "dashboard.viewAll": "View All",
    "dashboard.noData": "No Data",
    "dashboard.avgPrice": "Avg Price",
    "dashboard.trend": "Trend",
    "dashboard.heat": "Heat",
    "dashboard.risk": "Risk",
    "dashboard.trend30d": "30-day trend",
    "dashboard.monthlyTrendJudgment": "Monthly price trend",
    "dashboard.demandActivity": "Procurement demand activity",
    "dashboard.riskAssessment": "Procurement decision risk",
    "dashboard.ruleBased30d": "Rule-based · 30-day volatility",
    "dashboard.dataUpdatedPrefix": "Updated: ",
    "dashboard.priceSourcePrefix": "Price source: ",
    "dashboard.invSourcePrefix": "Inventory source: ",
    "dashboard.sourcePrefix": "Source: ",
    "dashboard.commodityCoverage": "Commodity Coverage",
    "dashboard.varietiesUnit": "varieties",
    "dashboard.modelAccuracy": "Model Accuracy",
    "dashboard.excellent": "Excellent",
    "dashboard.mcpTools": "MCP Tools",
    "dashboard.countUnit": "",
    "dashboard.enterpriseAccess": "Enterprise Access",
    "dashboard.householdsUnit": "",
    "dashboard.expanding": "Expanding",
    "dashboard.selected": "Selected",
    "dashboard.switch": "Switch",
    "dashboard.marketInsight": "Market Insight",
    "dashboard.deepAnalysis": "Deep Analysis",
    "dashboard.priceGraph": "Price Knowledge Graph",
    "dashboard.energyFlow": "Energy Flow",
    "dashboard.weeklyReport": "Weekly Report",
    "dashboard.enterprisePricePredictions": "Enterprise Price Predictions",
    "dashboard.avgPredictedPricePrefix": "Avg predicted price: ",
    "dashboard.perTon": "/ton",
    "dashboard.more": "More",
    "dashboard.details": "Details",
    "dashboard.loadingMarket": "Loading market data...",
    "dashboard.loadFailed": "Failed to load data",
    "dashboard.noCommodityDataPrefix": "No ",
    "dashboard.noCommodityDataSuffix": " price data",
    "dashboard.refreshingPrefix": "Refreshing ",
    "dashboard.refreshingSuffix": " data...",
    "dashboard.spotAvg": " spot average",
    "dashboard.simulatedData": "Simulated",
    "dashboard.modelDerived": "Model-derived",
    "dashboard.realData": "Real data",
    "dashboard.priceSeriesCalc": "price series calc",
    "dashboard.freshness.unknown": "Unknown",
    "dashboard.freshness.today": "Updated today",
    "dashboard.freshness.oneDayAgo": "1 day ago",
    "dashboard.freshness.daysAgoSuffix": " days ago",
    "dashboard.heat.hot": "Hot",
    "dashboard.heat.active": "Active",
    "dashboard.heat.mild": "Mild",
    "dashboard.heat.noData": "No Data",
    "dashboard.heatLabel.hot": "High demand",
    "dashboard.heatLabel.balanced": "Balanced",
    "dashboard.heatLabel.general": "General demand",
    "dashboard.heatLabel.noData": "Awaiting inventory data",
    "dashboard.riskLabel.volatile": "Volatile",
    "dashboard.riskLabel.watch": "Watch trend",
    "dashboard.riskLabel.stable": "Relatively stable",
    "dashboard.trend.up": "Up",
    "dashboard.trend.down": "Down",
    "dashboard.trend.flat": "Volatile",
    "dashboard.commodityList": "Sulfur · Phosphate · Potash · Urea",
    "dashboard.mcpToolsDesc": "Query · Predict · Compare · Accuracy",
    "dashboard.graph.price": "Price",
    "dashboard.graph.supply": "Supply",
    "dashboard.graph.demand": "Demand",
    "dashboard.graph.cost": "Cost",
    "dashboard.graph.policy": "Policy",

    // Market Analysis
    "marketAnalysis.title": "Market Analysis",
    "marketAnalysis.desc": "Price Tracking, Comparison & Model Accuracy",
    "marketAnalysis.tracker": "Tracker",
    "marketAnalysis.commodities": "Commodity Comparison",
    "marketAnalysis.accuracy": "Accuracy Analysis",

    // Reports
    "reports.title": "Procurement Reports",
    "reports.trend.up": "Up",
    "reports.trend.slightUp": "Slight Up",
    "reports.trend.down": "Down",
    "reports.trend.slightDown": "Slight Down",
    "reports.trend.stable": "Stable",
    "reports.trend.volatile": "Volatile",
    "reports.recommend.stockUp": "Stock Up",
    "reports.recommend.urgent": "Urgent Purchase",
    "reports.recommend.moderate": "Moderate Stock",
    "reports.recommend.wait": "Wait",
    "reports.recommend.asNeeded": "As Needed",
    "reports.risk.high": "High",
    "reports.risk.medium": "Medium",
    "reports.risk.low": "Low",
    "reports.riskSuffix": " Risk",
    "reports.exportWord": "Export Word",
    "reports.exportExcel": "Export Excel",
    "reports.discussInChat": "Discuss in Chat",
    "reports.searchPlaceholder": "Search reports...",
    "reports.filterByType": "Filter by Type",
    "reports.filterByRisk": "Filter by Risk",
    "reports.filterByTrend": "Filter by Trend",
    "reports.all": "All",
    "reports.generateReport": "Generate Report",
    "reports.keyword": "Keyword",
    "reports.clearFilters": "Clear",
    "reports.noReports": "No Reports",
    "reports.priceChart": "Price Chart",

    // Enterprise Management
    "enterpriseManage.title": "Enterprise Management",
    "enterpriseManage.addEnterprise": "Add Enterprise",
    "enterpriseManage.importExcel": "Import Excel",
    "enterpriseManage.downloadTemplate": "Download Template",
    "enterpriseManage.deleteEnterprise": "Delete Enterprise",
    "enterpriseManage.editEnterprise": "Edit Enterprise",
    "enterpriseManage.searchPlaceholder": "Search enterprises...",
    "enterpriseManage.noEnterprises": "No Enterprises",
    "enterpriseManage.confirmDelete": "Are you sure you want to delete this enterprise?",
    "enterpriseManage.createEnterprise": "Create Enterprise",
    "enterpriseManage.updateEnterprise": "Update Enterprise",
    "enterpriseManage.enterpriseName": "Enterprise Name",
    "enterpriseManage.enterpriseCode": "Enterprise Code",
    "enterpriseManage.shortDescription": "Short Description",
    "enterpriseManage.color": "Color",
    "enterpriseManage.industry": "Industry",
    "enterpriseManage.province": "Province",
    "enterpriseManage.city": "City",
    "enterpriseManage.importSuccess": "Import Successful",
    "enterpriseManage.importPartial": "Partial Import Successful",
    "enterpriseManage.enterpriseNamePlaceholder": "Enter enterprise name",
    "enterpriseManage.enterpriseCodePlaceholder": "Enter enterprise code (English)",
    "enterpriseManage.shortDescriptionPlaceholder": "Enter short description",
    "enterpriseManage.desc": "Manage enterprise information for analysis and import new enterprises",
    "enterpriseManage.totalPrefix": "Total: ",
    "enterpriseManage.totalSuffix": " enterprises",
    "enterpriseManage.preset": "Preset",
    "enterpriseManage.unknownRegion": "Unknown region",
    "enterpriseManage.capacity": "Capacity: ",
    "enterpriseManage.tenKtonPerYear": " 10k tons/year",
    "enterpriseManage.transport": "Transport: ",
    "enterpriseManage.stock": "Stock: ",
    "enterpriseManage.ton": " tons",
    "enterpriseManage.strategy": "Strategy: ",
    "enterpriseManage.viewDetailLink": "View impact factor weights and prediction trends →",
    "enterpriseManage.dialogEditDesc": "Modify enterprise information",
    "enterpriseManage.dialogAddDesc": "Fill in new enterprise info. Fields marked * are required",
    "enterpriseManage.enterpriseFullName": "Full name",
    "enterpriseManage.codeExamplePlaceholder": "e.g. example_corp",
    "enterpriseManage.location": "Location",
    "enterpriseManage.locationPlaceholder": "e.g. East China",
    "enterpriseManage.provincePlaceholder": "e.g. Shandong",
    "enterpriseManage.capacityLabel": "Capacity (10k tons/year)",
    "enterpriseManage.transportMode": "Transport mode",
    "enterpriseManage.inventoryStrategy": "Inventory strategy",
    "enterpriseManage.mainProducts": "Main products",
    "enterpriseManage.productsPlaceholder": "Comma-separated, e.g. MAP, Urea",
    "enterpriseManage.customerRegions": "Customer regions",
    "enterpriseManage.regionsPlaceholder": "Comma-separated, e.g. East China, South China",
    "enterpriseManage.description": "Description",
    "enterpriseManage.descriptionPlaceholder": "Describe the enterprise in detail...",
    "enterpriseManage.shortDescPlaceholder": "Shown in sidebar",
    "enterpriseManage.uiColor": "UI color",
    "enterpriseManage.inventorySection": "Inventory & Procurement",
    "enterpriseManage.currentStock": "Current stock (tons)",
    "enterpriseManage.maxCapacity": "Max storage (tons)",
    "enterpriseManage.safetyDays": "Safety stock days",
    "enterpriseManage.avgConsumption": "Avg consumption (tons/day)",
    "enterpriseManage.supplierCount": "Supplier count",
    "enterpriseManage.portDistance": "Distance to port (km)",
    "enterpriseManage.priceConfigSection": "Price Prediction Config",
    "enterpriseManage.basePrice": "Base price",
    "enterpriseManage.lastPurchaseDate": "Last purchase date",
    "enterpriseManage.importDesc": "Import files in JSON or CSV format",
    "enterpriseManage.uploadHint": "Click to upload or drag files here",
    "enterpriseManage.importFormats": "Supports JSON, CSV formats",
    "enterpriseManage.successCount": "Success: ",
    "enterpriseManage.skippedCount": "Skipped: ",
    "enterpriseManage.failedCount": "Failed: ",
    "enterpriseManage.error.fetchFailed": "Failed to fetch enterprise list",
    "enterpriseManage.error.saveFailed": "Failed to save enterprise",
    "enterpriseManage.error.deleteFailed": "Failed to delete enterprise",
    "enterpriseManage.error.importFailed": "Import failed, please check the file format",
    "enterpriseManage.error.invalidFile": "Please upload a JSON or CSV file",
    "enterpriseManage.error.staticDelete": "Static enterprises (HX Group, HY Group, TC Group) cannot be deleted",
    "enterpriseManage.color.cyan": "Cyan",
    "enterpriseManage.color.violet": "Violet",
    "enterpriseManage.color.amber": "Amber",
    "enterpriseManage.color.emerald": "Emerald",
    "enterpriseManage.color.rose": "Rose",
    "enterpriseManage.color.blue": "Blue",
    "enterpriseManage.transport.water": "Water",
    "enterpriseManage.transport.rail": "Rail",
    "enterpriseManage.transport.road": "Road",
    "enterpriseManage.strategy.aggressive": "Aggressive",
    "enterpriseManage.strategy.moderate": "Moderate",
    "enterpriseManage.strategy.conservative": "Conservative",

    // Enterprise List
    "enterprises.title": "Enterprise Analysis",
    "enterprises.searchPlaceholder": "Search by name, industry, product...",
    "enterprises.filterIndustry": "Filter by Industry",
    "enterprises.filterProvince": "Filter by Province",
    "enterprises.allIndustries": "All Industries",
    "enterprises.allProvinces": "All Provinces",
    "enterprises.total": "Total Enterprises",
    "enterprises.listed": "Listed",
    "enterprises.unlisted": "Unlisted",
    "enterprises.industries": "Industries",
    "enterprises.provinces": "Provinces",
    "enterprises.lastUpdated": "Last Updated",
    "enterprises.viewDetail": "View Details",
    "enterprises.website": "Website",
    "enterprises.products": "Main Products",
    "enterprises.employees": "Employees",
    "enterprises.founded": "Founded",
    "enterprises.revenue": "Annual Revenue",
    "enterprises.sampleNote": "Sample data · anonymized · Last updated: ",
    "enterprises.totalPrefix": "Total: ",
    "enterprises.totalSuffix": " enterprises",
    "enterprises.filterTitle": "Filters",
    "enterprises.foundPrefix": "Found ",
    "enterprises.foundSuffix": " enterprises",
    "enterprises.listedBadge": "Listed",
    "enterprises.mainProductsLabel": "Main Products: ",
    "enterprises.revenueLabel": "Revenue: ",
    "enterprises.employeesLabel": "Employees: ",
    "enterprises.websiteLink": "Visit Website →",

    // Agent Chat
    "chat.title": "Agent Assistant",
    "chat.newConversation": "New Conversation",
    "chat.deleteConversation": "Delete Conversation",
    "chat.inputPlaceholder": "Type your question...",
    "chat.send": "Send",
    "chat.copy": "Copy",
    "chat.regenerate": "Regenerate",
    "chat.thinking": "Thinking...",
    "chat.noConversations": "No Conversations",
    "chat.uploadImage": "Upload Image",
    "chat.clearConversation": "Clear Conversation",
    "chat.welcomeTitle": "Sulfur Procurement AI Assistant",
    "chat.welcomeDesc": "I can help you analyze market trends, predict price movements, and generate procurement recommendations",
    "chat.suggestions": "Try these questions",
    "chat.exportReport": "Export Report",
    "chat.regenerateAnswer": "Regenerate Answer",
    "chat.generateReport": "Generate Report",
    "chat.copied": "Copied",
    "chat.mayAlsoAsk": "You may also want to know:",
    "chat.agentThinking": "Agent thinking...",
    "chat.login": "Sign In",
    "chat.noHistory": "No chat history",
    "chat.advisorTitle": "Sulfur Procurement Advisor",
    "chat.onlineStatus": "Online · always here to help",
    "chat.systemArchitecture": "System Architecture",
    "chat.quickQuestions": "Quick Questions",
    "chat.usageTips": "Usage Tips",
    "chat.howToUse": "How to better use the assistant",
    "chat.deepAnalysis": "Deep Analysis",
    "chat.advancedTips": "Advanced questioning tips",
    "chat.subtitle": "AI-powered smart procurement decision support",
    "chat.synced": "History synced",
    "chat.savePrompt": "Sign in to save conversations",
    "chat.inputPlaceholderImage": "Add description or send directly...",
    "chat.inputPlaceholderPaste": "Type your question (paste images supported)...",
    "chat.previewImage": "Preview image",
    "chat.noContentReport": "No conversation content to generate a report",
    "chat.reportGeneratedPrefix": "Report generated: ",
    "chat.reportFailed": "Failed to generate report, please try again later",
    "chat.suggested.trend": "What's the current sulfur market trend?",
    "chat.suggested.weekAdvice": "What's the procurement advice for the coming week?",
    "chat.suggested.inventory": "Does inventory level need adjustment?",
    "chat.suggested.supplierCompare": "Compare quotes from major suppliers",
    "chat.suggested.volatilityCause": "Analyze the reasons for recent price volatility",
    "chat.suggested.nextMonth": "Predict next month's price trend",
    "chat.suggested.report": "Generate a procurement decision report",
    "chat.suggested.freightCost": "Impact of international freight on cost",
    "chat.followUp.price.rise": "Will prices keep rising?",
    "chat.followUp.price.factors": "What factors affect price volatility?",
    "chat.followUp.price.yoy": "How does it compare to last year?",
    "chat.followUp.price.timing": "When is the best time to purchase?",
    "chat.followUp.stock.turnover": "What's the current inventory turnover days?",
    "chat.followUp.stock.safety": "What's the recommended safety stock level?",
    "chat.followUp.stock.cost": "How to optimize inventory cost?",
    "chat.followUp.stock.port": "How is inventory distributed across ports?",
    "chat.followUp.purchase.nowOrWait": "Should we purchase now or wait?",
    "chat.followUp.purchase.quantity": "What's the recommended purchase quantity?",
    "chat.followUp.purchase.splitOrCentral": "Diversified or centralized purchasing?",
    "chat.followUp.purchase.risk": "How to reduce procurement risk?",
    "chat.followUp.trend.month": "Trend forecast for the next month?",
    "chat.followUp.trend.seasonal": "How do seasonal factors affect it?",
    "chat.followUp.trend.international": "How is the international market trending?",
    "chat.followUp.trend.demand": "What's the demand-side trend?",
    "chat.followUp.risk.main": "What are the main risk factors?",
    "chat.followUp.risk.priceHedge": "How to hedge against price risk?",
    "chat.followUp.risk.supplyChain": "How to handle supply chain risk?",
    "chat.followUp.risk.exchange": "How much does exchange rate fluctuation matter?",
    "chat.followUp.default.elaborate": "Can you explain in more detail?",
    "chat.followUp.default.basis": "What's the data basis for this conclusion?",
    "chat.followUp.default.action": "What actions do you recommend?",
    "chat.tip.specific": "Be specific and include a time range",
    "chat.tip.table": "Ask for data comparison tables",
    "chat.tip.followUp": "Supports follow-up and multi-turn conversations",
    "chat.tip.report": "Request procurement recommendation reports",
    "chat.tip.clickFollowUp": "Click follow-up buttons to dig deeper",
    "chat.tip.explainSource": "Ask to explain data sources and calculation methods",
    "chat.tip.scenarios": "Ask for analysis under different scenarios",
    "chat.tip.compare": "Request comparison of multiple suppliers/regions",
    "chat.tip.risks": "Ask the AI to list risks and uncertainties",

    // API Console
    "apiConsole.title": "API Console",
    "apiConsole.desc": "API Key Management & Documentation",
    "apiConsole.createKey": "Create API Key",
    "apiConsole.keyName": "Key Name",
    "apiConsole.keyNamePlaceholder": "Enter key name",
    "apiConsole.create": "Create",
    "apiConsole.cancel": "Cancel",
    "apiConsole.yourKeys": "Your API Keys",
    "apiConsole.noKeys": "No API Keys",
    "apiConsole.quota": "Quota",
    "apiConsole.used": "Used",
    "apiConsole.remaining": "Remaining",
    "apiConsole.copyKey": "Copy Key",
    "apiConsole.copied": "Copied",
    "apiConsole.deleteKey": "Delete Key",
    "apiConsole.resetKey": "Reset Key",
    "apiConsole.keyCreated": "API Key Created",
    "apiConsole.keyCreatedWarning": "Save this API Key securely. It will not be shown again.",
    "apiConsole.confirmDeleteKey": "Are you sure you want to delete this API Key?",
    "apiConsole.confirmResetKey": "Are you sure you want to reset this API Key? The old key will be invalidated immediately.",
    "apiConsole.apiDocs": "API Documentation",
    "apiConsole.baseUrl": "Base URL",
    "apiConsole.authMethod": "Authentication",
    "apiConsole.rateLimit": "Rate Limit",
    "apiConsole.requestsPerMinute": "requests/min",
    "apiConsole.endpoints": "Endpoints",
    "apiConsole.createKeyBtn": "Create Key",
    "apiConsole.quotaInfo": "API Quota (remaining this month)",
    "apiConsole.free": "Free",
    "apiConsole.paid": "Paid",
    "apiConsole.totalPrefix": "Total: ",
    "apiConsole.totalSuffix": " calls",
    "apiConsole.emptyDesc": "Create an API Key to start using the API",
    "apiConsole.inactive": "Disabled",
    "apiConsole.createdAt": "Created ",
    "apiConsole.lastUsed": " · Last used ",
    "apiConsole.reset": "Reset",
    "apiConsole.limitReached": "API Key limit reached (max 5)",
    "apiConsole.keyNamePlaceholderExample": "e.g. Production Key",
    "apiConsole.keyNameDesc": "Set an easily recognizable name for this API Key",
    "apiConsole.copy": "Copy",
    "apiConsole.done": "Done",
    "apiConsole.resetTitle": "API Key Reset",
    "apiConsole.resetWarning": "Old key is now invalid. Save the new key.",
    "apiConsole.createFailed": "Failed to create",
    "apiConsole.deleteFailed": "Failed to delete",
    "apiConsole.resetFailed": "Failed to reset",
    "apiConsole.tabPrices": "Prices",
    "apiConsole.tabPredict": "Prediction",
    "apiConsole.tabDecision": "Decision",
    "apiConsole.tabInventory": "Inventory",
    "apiConsole.tabNews": "News",
    "apiConsole.tabChat": "AI Chat",
    "apiConsole.descPrices": "Get sulfur price history",
    "apiConsole.descPredict": "Predict future sulfur prices",
    "apiConsole.descDecision": "Get procurement decision advice",
    "apiConsole.descInventory": "Get port inventory data",
    "apiConsole.descNews": "Get market news",
    "apiConsole.descChat": "Chat with the AI assistant",
    "apiConsole.requestParams": "Request Parameters",
    "apiConsole.requestBody": "Request Body",
    "apiConsole.exampleCode": "Example Code",
    "apiConsole.paramName": "Parameter",
    "apiConsole.paramType": "Type",
    "apiConsole.paramDesc": "Description",
    "apiConsole.startDate": "Start date (YYYY-MM-DD)",
    "apiConsole.endDate": "End date (YYYY-MM-DD)",
    "apiConsole.regionFilter": "Filter by region",
    "apiConsole.marketFilter": "Filter by market",
    "apiConsole.portFilter": "Filter by port",
    "apiConsole.keywordFilter": "Filter by keyword",
    "apiConsole.returnCount30": "Return count (default 30)",
    "apiConsole.returnCount20": "Return count (default 20)",

    // API Keys Page
    "apiKeys.title": "API Keys Management",
    "apiKeys.createKey": "Create API Key",
    "apiKeys.noKeys": "No API Keys yet. Click the button above to create one.",
    "apiKeys.active": "Active",
    "apiKeys.inactive": "Inactive",
    "apiKeys.neverUsed": "Never Used",
    "apiKeys.createdAt": "Created",
    "apiKeys.lastUsed": "Last Used",
    "apiKeys.expiresAt": "Expires",
    "apiKeys.quotaTitle": "Quota Usage",
    "apiKeys.requestsUsed": "Requests Used",
    "apiKeys.desc": "Manage your API keys and quota",
    "apiKeys.apiDocs": "API Docs",
    "apiKeys.quotaBalance": "Quota Balance",
    "apiKeys.freeQuota": "Free Quota",
    "apiKeys.paidQuota": "Paid Quota",
    "apiKeys.totalRemaining": "Total Remaining",
    "apiKeys.createNewKey": "Create New API Key",
    "apiKeys.keyNamePlaceholder": "Key name (e.g. Production)",
    "apiKeys.saveKeyWarning": "Please save this API Key",
    "apiKeys.keyShownOnce": "This key is shown only once. You won't be able to view it again after closing.",
    "apiKeys.yourKeys": "Your API Keys",
    "apiKeys.maxKeys": "You can create up to 5 API Keys",
    "apiKeys.noKeysHint": "No API Keys yet. Please create one.",
    "apiKeys.createdAtLabel": "Created: ",
    "apiKeys.lastUsedLabel": "Last used: ",
    "apiKeys.error.nameRequired": "Please enter a key name",
    "apiKeys.error.createRetry": "Failed to create, please try again later",
    "apiKeys.error.resetRetry": "Failed to reset, please try again later",
    "apiKeys.confirmReset": "The old key will be invalidated after reset. Continue?",

    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.export": "Export",
    "common.import": "Import",
    "common.create": "Create",
    "common.close": "Close",
    "common.confirm": "Confirm",
    "common.cancel": "Cancel",
    "common.retry": "Retry",
    "common.noData": "No Data",
    "common.success": "Success",
    "common.failed": "Failed",
    "common.viewDetail": "View Details",
    "common.back": "Back",
    "common.yes": "Yes",
    "common.no": "No",

    // Landing Page
    "landing.hero.title": "AI-Powered Smart Decisions",
    "landing.hero.subtitle": "Sulfur Procurement",
    "landing.hero.desc": "Intelligent Decision System",
    "landing.hero.cta": "Get Started",
    "landing.hero.learnMore": "Learn More",
    "landing.features.title": "Core Capabilities",
    "landing.features.subtitle": "Four Smart Modules",
    "landing.stats.accuracy": "Prediction Accuracy",
    "landing.stats.enterprises": "Enterprises Served",
    "landing.stats.data": "Historical Data",
    "landing.stats.monitoring": "Real-time Monitoring",
    "landing.about.title": "Why Choose Us",
    "landing.cta.title": "Start Your Smart Procurement Journey",
    "landing.cta.button": "Get Started Free",
  },
}

interface LanguageContextValue {
  lang: Lang
  setLang: (lang: Lang) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: "zh",
  setLang: () => {},
  t: (key: string) => key,
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("zh")
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    const stored = localStorage.getItem("lang")
    if (stored === "en" || stored === "zh") {
      setLangState(stored)
    }
    setMounted(true)
  }, [])

  const setLang = useCallback((l: Lang) => {
    setLangState(l)
    localStorage.setItem("lang", l)
  }, [])

  const t = useCallback(
    (key: string) => translations[lang]?.[key] || key,
    [lang]
  )

  // Prevent hydration mismatch by rendering with "zh" until mounted
  if (!mounted) {
    return (
      <LanguageContext.Provider value={{ lang: "zh", setLang, t: (key: string) => translations.zh[key] || key }}>
        {children}
      </LanguageContext.Provider>
    )
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}

export { translations }